version: '3'

services:
  rabbitmq:
    image: rabbitmq:latest
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: default
      RABBITMQ_DEFAULT_PASS: defaultpass
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
    ports:
      - "5672:5672"
      - "15672:15672"